apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-aggregator-conf
  namespace: vector
data:
  vector.toml: |2+

    data_dir                                = "/var/lib/vector"


    [api]
      enabled                               = true
      address                               = "127.0.0.1:8686"
      playground                            = true


    [sources.vector_tcp]
      type                                 = "vector"
      address                              = "0.0.0.0:9000"


    [transforms.swimlanes]
      type                                 = "swimlanes"
      inputs                               = ["vector_tcp"]

    [transforms.swimlanes.lanes.kubernetes_logs]
      type                                 = "check_fields"
      "file.starts_with"                   = "/var/log/pods/"


    [sinks.kafka]
      type = "kafka"
      inputs = ["swimlanes.kubernetes_logs"]
      bootstrap_servers = "my-cluster-kafka-bootstrap.amq:9092"
      topic = "vector-topic"
      encoding.codec = "json"
